# Generated by Django 5.2.8 on 2025-11-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('interview_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('panel', models.IntegerField(choices=[(1, 'Panel 1'), (2, 'Panel 2')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['interview_date', 'start_time'],
                'unique_together': {('interview_date', 'start_time', 'panel')},
            },
        ),
    ]
