# Generated by Django 5.2.8 on 2025-11-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='panel',
            field=models.IntegerField(choices=[(1, 'Panel 1'), (2, 'Panel 2'), (3, 'No Slots Available')], default=1),
        ),
    ]
